### ISSUE TITLE
Method 2 does not try any word

### ISSUE THREAD

**Issue by PedroLvr** [MaxCamillo/android-keystore-password-recover#14]
Hello,
I'm having some problem, when I run the program in method 3, it works fine, but in method 2 it does not try any word, just jumps out. Below the log: 

```
$ java -jar Android_Keystore_Password_Recover_1.07.jar -m 2 -k financeiro.keystore -d dictionary.txt

Number of keys in keystore: 1
Found alias: financeiro
Creation Date: Fri Nov 25 00:04:35 BOT 2016

Start dictionary attack on key!!

Current Pass:  || est. 0 Pass/Sec

No matching key in wordlist; try an other wordlist!!

For updates visit http://maxcamillo.github.io/android-keystore-password-recover/
```

Am I doing something wrong? Hope some response.

**Comment by MaxCamillo** [comment]
Hey,

 

maybe your wordlist is empty?

 

Von: Pedro Lavôr [mailto:notifications@github.com] 
Gesendet: Dienstag, 16. Mai 2017 21:15
An: MaxCamillo/android-keystore-password-recover <android-keystore-password-recover@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [MaxCamillo/android-keystore-password-recover] Method 2 does not try any word (#14)

 

Hello,
I'm having some problem, when I run the program in method 3, it works fine, but in method 2 it does not try any word, just jumps out. Below the log:

$ java -jar Android_Keystore_Password_Recover_1.07.jar -m 2 -k financeiro.keystore -d dictionary.txt
 
Number of keys in keystore: 1
Found alias: financeiro
Creation Date: Fri Nov 25 00:04:35 BOT 2016
 
Start dictionary attack on key!!
 
Current Pass:  || est. 0 Pass/Sec
 
No matching key in wordlist; try an other wordlist!!
 
For updates visit http://maxcamillo.github.io/android-keystore-password-recover/

Am I doing something wrong? Hope some response.

**Comment by PedroLvr** [comment]
Hi, thanks for the reply.

Like I said, I've tested the same wordlist in method 3 and worked fine, shows each password it's trying and save into resume file every 3 passwords, I can see all that in terminal. But the method 2 don't even try once.

Did you try in your computer after my report? Is it just me?
If it's just me, that's ok, I've already decided to create a new keystore, so no hurry to solve.

**Comment by MaxCamillo** [comment]
So, how many passwords are in your dictionary.txt file?

 

Von: Pedro Lavôr [mailto:notifications@github.com] 
Gesendet: Mittwoch, 17. Mai 2017 20:32
An: MaxCamillo/android-keystore-password-recover <android-keystore-password-recover@noreply.github.com>
Cc: MaxCamillo <max.eisele@student.kit.edu>; Comment <comment@noreply.github.com>
Betreff: Re: [MaxCamillo/android-keystore-password-recover] Method 2 does not try any word (#14)

 

Hi, thanks for the reply.

Like I said, I've tested the same wordlist in method 3 and worked fine, shows each password it's trying and save into resume file every 3 passwords, I can see all that in terminal. But the method 2 don't even try once.

Did you try in your computer after my report? Is it just me?
If it's just me, that's ok, I've already decided to create a new keystore, so no hurry to solve.

**Comment by PedroLvr** [comment]
7 words + 3 special characters...
financeiro, gestor, ideias, ticketphone, android, keystore, keytool, -, .(dot), (space)

**Comment by MaxCamillo** [comment]
So, these 7 words are not your password. In this Mode, only all words in the list are tried and nothing else

Von meinem Sony Xperia™-Smartphone gesendet

---- Pedro Lavôr schrieb ----


7 words + 3 special characters...
financeiro, gestor, ideias, ticketphone, android, keystore, keytool, -, .(dot), (space)

**Comment by PedroLvr** [comment]
So the words in the list are not permuted and mixed in method 2? I thought the difference between 2 and 3 was the ramdom numbers added.
Is possible to method 3 do not add numbers?
Because I'm sure there is no numbers, I wanna only permute between my words.

**Comment by MaxCamillo** [comment]
Yes, exactly. I think currently it is not Supported, but you have the source code, so o think its not a big issue

Von meinem Sony Xperia™-Smartphone gesendet

---- Pedro Lavôr schrieb ----


So the words in the list are not permuted and mixed in method 2? I thought the difference between 2 and 3 was the ramdom numbers added.
Is possible to method 3 do not add numbers?
Because I'm sure there is no numbers, I wanna only permute between my words.

**Comment by PedroLvr** [comment]
All right @MaxCamillo, no problem.

Thank you for the suport!
Closing this.
